[package]
name = "osu-microapi"
version = "0.2.0"
edition = "2021"

[profile.release]
lto = 'thin'

[dependencies]
isahc = "1.7.2"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
tiny_http = "0.9.0"
